# Generated by Django 6.0.2 on 2026-09-09 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('environment', models.CharField(default='production', max_length=20)),
                ('host', models.CharField(default='devforge_local', max_length=32)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('testing', 'Testing'), ('ready', 'Ready to publish'), ('publishing', 'Publishing'), ('live', 'Live'), ('needs_attention', 'Needs attention'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('artifact_dir', models.CharField(blank=True, max_length=1024)),
                ('commit', models.CharField(blank=True, max_length=40)),
                ('health', models.CharField(default='unknown', max_length=16)),
                ('health_detail', models.CharField(blank=True, max_length=255)),
                ('readiness', models.PositiveSmallIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='publishing.publishversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.SlugField(max_length=63, unique=True)),
                ('site_type', models.CharField(default='business', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='publishversion',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='publishing.website'),
        ),
    ]
