# Generated by Django 6.0.2 on 2026-09-09 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('verification_token', models.CharField(max_length=64)),
                ('required_records', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(default='pending', max_length=16)),
                ('ssl_status', models.CharField(default='none', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_domains', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='publishing.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
