# Generated by Django 6.0.2 on 2026-09-09 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_customdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_suffix', models.CharField(blank=True, max_length=120)),
                ('default_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.CharField(blank=True, max_length=1024)),
                ('robots_allow', models.BooleanField(default=True)),
                ('sitemap_enabled', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='publishing.website')),
            ],
        ),
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('canonical', models.CharField(blank=True, max_length=1024)),
                ('ai_generated', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='publishing.seoconfig')),
            ],
            options={
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('config', 'path'), name='uniq_pageseo_path')],
            },
        ),
    ]
