# Generated by Django 6.0.2 on 2026-09-09 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0005_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(default='desktop', max_length=16)),
                ('session_key', models.CharField(max_length=32)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='publishing.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['website', 'day'], name='publishing__website_b0b6d3_idx')],
            },
        ),
    ]
