# Generated by Django 6.0.2 on 2026-09-09 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0006_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='up', max_length=8)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checks', to='publishing.publishversion')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='publishing.website')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['website', 'checked_at'], name='publishing__website_be4d69_idx')],
            },
        ),
    ]
