# Generated by Django 6.0.2 on 2026-09-09 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0007_healthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('blog', 'Blog'), ('article', 'Articles'), ('faq', 'FAQs'), ('service', 'Services'), ('team', 'Team'), ('testimonial', 'Testimonials'), ('product', 'Products'), ('project', 'Projects'), ('page', 'Pages')], default='blog', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='publishing.website')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=1024)),
                ('published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publishing.contentcollection')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contentcollection',
            constraint=models.UniqueConstraint(fields=('website', 'slug'), name='uniq_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='uniq_item_slug'),
        ),
    ]
