# Generated by Django 6.0.2 on 2026-09-09 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0008_contentcollection_contentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('key_authorization', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acme_challenges', to='publishing.customdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
