# Generated by Django 6.0.2 on 2026-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0010_order_payment_product_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
