# Generated by Django 6.0.2 on 2026-09-09 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0012_product_stock_product_track_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(default='percent', max_length=8)),
                ('percent_off', models.PositiveSmallIntegerField(default=0)),
                ('amount_off_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('min_subtotal_cents', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='publishing.website')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='publishing.discountcode'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('website', 'code'), name='uniq_discount_code'),
        ),
    ]
