# Generated by Django 6.0.2 on 2026-09-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0015_order_tax_cents_taxrate_order_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='publishing.asset'),
        ),
    ]
