# Generated by Django 6.0.2 on 2026-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0016_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('api', 'API'), ('pos', 'POS'), ('whatsapp', 'WhatsApp'), ('admin', 'Admin')], default='web', max_length=16),
        ),
    ]
