# Generated by Django 6.0.2 on 2026-09-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
