# Generated by Django 6.0.2 on 2026-09-07 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('awaiting_approval', 'Awaiting approval'), ('implementing', 'Implementing'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('estimate', models.JSONField(blank=True, default=dict)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('task_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
