# Generated by Django 6.0.2 on 2026-09-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
        ('database_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='migration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='database_agent.databasemigration'),
        ),
    ]
