# Generated by Django 6.0.2 on 2026-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0003_changerequest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='base_commit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='result_commit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('awaiting_approval', 'Awaiting approval'), ('implementing', 'Implementing'), ('done', 'Done'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='draft', max_length=32),
        ),
    ]
