# Generated by Django 6.0.2 on 2026-09-08 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('alter', 'Alter'), ('drop', 'Drop'), ('rename', 'Rename'), ('index', 'Index'), ('constraint', 'Constraint'), ('data', 'Data migration')], max_length=20)),
                ('up_sql', models.TextField()),
                ('down_sql', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('applied', 'Applied'), ('rolled_back', 'Rolled back'), ('failed', 'Failed')], default='planned', max_length=24)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('execution_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_db_migrations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_db_migrations', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='database_agent.databasemigration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_migrations', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'version'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version'), name='uniq_migration_version_per_project')],
            },
        ),
    ]
