from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.test import TestCase

from apps.organizations.models import Membership, Organization, Role

User = get_user_model()


class OrganizationModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        org = Organization.objects.create(name="Acme Corp")
        self.assertEqual(org.slug, "acme-corp")

    def test_slug_collisions_are_disambiguated(self):
        a = Organization.objects.create(name="Acme")
        b = Organization.objects.create(name="Acme")
        self.assertEqual(a.slug, "acme")
        self.assertEqual(b.slug, "acme-2")

    def test_explicit_slug_is_respected(self):
        org = Organization.objects.create(name="Acme", slug="custom")
        self.assertEqual(org.slug, "custom")


class MembershipTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name="Acme")
        self.user = User.objects.create_user(
            email="member@example.com", password="pw12345!"
        )

    def test_add_member_defaults_to_member_role(self):
        m = self.org.add_member(self.user)
        self.assertEqual(m.role, Role.MEMBER)
        self.assertFalse(m.can_manage)

    def test_add_member_is_idempotent(self):
        self.org.add_member(self.user, role=Role.OWNER)
        self.org.add_member(self.user)  # second call must not duplicate
        self.assertEqual(self.org.memberships.count(), 1)

    def test_owner_and_admin_can_manage(self):
        owner = self.org.add_member(self.user, role=Role.OWNER)
        self.assertTrue(owner.is_owner)
        self.assertTrue(owner.can_manage)

    def test_unique_membership_constraint(self):
        Membership.objects.create(organization=self.org, user=self.user)
        with self.assertRaises(IntegrityError):
            Membership.objects.create(organization=self.org, user=self.user)

    def test_members_reverse_relations(self):
        self.org.add_member(self.user, role=Role.ADMIN)
        self.assertIn(self.org, self.user.organizations.all())
        self.assertIn(self.user, self.org.members.all())
