# Generated by Django 6.0.2 on 2026-09-09 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_team_invitation_teammembership_team_members_and_more'),
        ('projects', '0002_project_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event', models.CharField(choices=[('pre_change', 'Before a change'), ('post_build', 'After a build'), ('pre_deploy', 'Before deploy'), ('post_deploy', 'After deploy')], max_length=16)),
                ('action', models.CharField(max_length=24)),
                ('blocking', models.BooleanField(default=True)),
                ('scope', models.CharField(default='global', max_length=8)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='projects.project')),
            ],
            options={
                'ordering': ['event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=8)),
                ('blocked', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='hooks.hook')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hook_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
