# Generated by Django 6.0.2 on 2026-09-09 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_team_invitation_teammembership_team_members_and_more'),
        ('projects', '0002_project_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('package_identifier', models.CharField(blank=True, max_length=255)),
                ('bundle_identifier', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('build_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_applications', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('harmony', 'HarmonyOS / Huawei')], max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('build_number', models.PositiveIntegerField()),
                ('artifact_format', models.CharField(blank=True, max_length=16)),
                ('artifact_path', models.CharField(blank=True, max_length=1024)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='release.mobileapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('build_number', models.PositiveIntegerField()),
                ('environment', models.CharField(default='production', max_length=32)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('build_ready', 'Build ready'), ('signing', 'Signing'), ('signed', 'Signed'), ('metadata_incomplete', 'Metadata incomplete'), ('ready_for_testing', 'Ready for testing'), ('testing', 'Testing'), ('ready_for_submission', 'Ready for submission'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('releasing', 'Releasing'), ('released', 'Released'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='draft', max_length=32)),
                ('readiness', models.PositiveSmallIntegerField(default=0)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='release.mobilebuild')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL)),
                ('mobile_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='release.mobileapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_approvals', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='release.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='release.release')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_events', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='release.release')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('harmony', 'HarmonyOS / Huawei')], max_length=16)),
                ('mode', models.CharField(choices=[('managed', 'DevForge-managed'), ('customer', 'Customer-managed')], default='managed', max_length=16)),
                ('credential_reference', models.CharField(blank=True, help_text='Opaque vault handle for signing material — NEVER a key/password.', max_length=255)),
                ('configured', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_configs', to='release.mobileapplication')),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('external_app_id', models.CharField(blank=True, max_length=255)),
                ('metadata_status', models.CharField(default='incomplete', max_length=32)),
                ('signing_status', models.CharField(default='not_configured', max_length=32)),
                ('release_status', models.CharField(default='none', max_length=32)),
                ('review_status', models.CharField(default='none', max_length=32)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('mobile_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_apps', to='release.mobileapplication')),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.AddField(
            model_name='release',
            name='store_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='release.storeapplication'),
        ),
        migrations.CreateModel(
            name='StoreConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('credential_type', models.CharField(blank=True, max_length=64)),
                ('credential_reference', models.CharField(blank=True, help_text='Opaque vault handle — NEVER a secret. Redact from logs.', max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('not_connected', 'Not connected'), ('incomplete', 'Connection incomplete'), ('connected', 'Connected')], default='not_connected', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_connections', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storeapplication',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_apps', to='release.storeconnection'),
        ),
        migrations.CreateModel(
            name='StoreMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('support_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='release.storeapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'key'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'key', 'version'), name='uniq_store_requirement_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='storeconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='uniq_org_store_provider'),
        ),
        migrations.AddConstraint(
            model_name='storeapplication',
            constraint=models.UniqueConstraint(fields=('mobile_application', 'provider'), name='uniq_app_store_provider'),
        ),
    ]
