# Generated by Django 6.0.2 on 2026-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemetadata',
            name='generated',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
