# Generated by Django 6.0.2 on 2026-09-09 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_storemetadata_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='screenshot', max_length=24)),
                ('screen_name', models.CharField(blank=True, max_length=255)),
                ('slot', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='schematic', max_length=16)),
                ('fmt', models.CharField(default='svg', max_length=8)),
                ('svg', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='release.storeapplication')),
            ],
            options={
                'ordering': ['slot', 'id'],
            },
        ),
    ]
