# Generated by Django 6.0.2 on 2026-09-09 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0004_changerequest_base_commit_and_more'),
        ('release', '0003_storeasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('source', models.CharField(default='manual', max_length=16)),
                ('raw_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('recommendation', models.CharField(blank=True, max_length=1000)),
                ('compliance_sensitive', models.BooleanField(default=False)),
                ('affected_capabilities', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='changes.changerequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_rejections', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='release.release')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
