# Generated by Django 6.0.2 on 2026-09-04 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('planning', 'Planning'), ('running', 'Running'), ('waiting_for_tool', 'Waiting for tool'), ('waiting_for_agent', 'Waiting for agent'), ('waiting_for_approval', 'Waiting for approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('blocked', 'Blocked')], default='queued', max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('credits', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='orchestrator.agenttask')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='orchestrator.agenttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='projects.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='orchestrato_project_ebb45b_idx'), models.Index(fields=['status'], name='orchestrato_status_8cf920_idx')],
            },
        ),
    ]
