# Generated by Django 6.0.2 on 2026-09-04 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('requirement', 'Requirement'), ('architecture', 'Architecture'), ('business_rule', 'Business rule'), ('tech_decision', 'Technical decision'), ('schema', 'Database schema'), ('api', 'API'), ('dependency', 'Dependency'), ('known_issue', 'Known issue'), ('agent_decision', 'Agent decision'), ('deployment', 'Deployment'), ('infrastructure', 'Infrastructure'), ('testing', 'Testing'), ('security', 'Security'), ('note', 'Note')], max_length=32)),
                ('key', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_entries', to='projects.project')),
            ],
            options={
                'ordering': ['kind', 'key'],
                'indexes': [models.Index(fields=['project', 'kind'], name='project_con_project_5c9ddb_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'kind', 'key'), name='unique_context_entry_per_project_kind')],
            },
        ),
    ]
