# Generated by Django 6.0.2 on 2026-09-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextentry',
            name='kind',
            field=models.CharField(choices=[('requirement', 'Requirement'), ('architecture', 'Architecture'), ('business_rule', 'Business rule'), ('tech_decision', 'Technical decision'), ('schema', 'Database schema'), ('api', 'API'), ('screen', 'Screen / UI'), ('dependency', 'Dependency'), ('known_issue', 'Known issue'), ('agent_decision', 'Agent decision'), ('deployment', 'Deployment'), ('infrastructure', 'Infrastructure'), ('testing', 'Testing'), ('security', 'Security'), ('note', 'Note')], max_length=32),
        ),
    ]
