# Generated by Django 6.0.2 on 2026-09-04 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'slug'), name='unique_workspace_slug_per_project'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('project',), name='one_default_workspace_per_project')],
            },
        ),
    ]
