from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.test import TestCase
from django.urls import reverse

from apps.organizations.models import Organization, Role
from apps.projects.models import Project

User = get_user_model()


class ProjectModelTests(TestCase):
    def setUp(self):
        self.org = Organization.objects.create(name="Acme")

    def test_slug_autogenerated_and_scoped_per_org(self):
        p = Project.objects.create(organization=self.org, name="Website")
        self.assertEqual(p.slug, "website")

    def test_same_slug_allowed_in_different_orgs(self):
        other = Organization.objects.create(name="Globex")
        a = Project.objects.create(organization=self.org, name="App")
        b = Project.objects.create(organization=other, name="App")
        self.assertEqual(a.slug, "app")
        self.assertEqual(b.slug, "app")  # different org, no collision

    def test_slug_collision_within_org(self):
        a = Project.objects.create(organization=self.org, name="App")
        b = Project.objects.create(organization=self.org, name="App")
        self.assertEqual(a.slug, "app")
        self.assertEqual(b.slug, "app-2")

    def test_duplicate_slug_in_same_org_rejected(self):
        Project.objects.create(organization=self.org, name="App", slug="app")
        with self.assertRaises(IntegrityError):
            Project.objects.create(organization=self.org, name="Other", slug="app")

    def test_ensure_default_workspace_is_idempotent(self):
        p = Project.objects.create(organization=self.org, name="App")
        w1 = p.ensure_default_workspace()
        w2 = p.ensure_default_workspace()
        self.assertEqual(w1, w2)
        self.assertEqual(p.workspaces.count(), 1)
        self.assertTrue(w1.is_default)
        self.assertEqual(w1.organization, self.org)


class ProjectAPITests(TestCase):
    def setUp(self):
        # org_a: alice is owner. org_b: bob is owner. carol: member of org_a only.
        self.alice = User.objects.create_user(email="alice@x.com", password="pw12345!")
        self.bob = User.objects.create_user(email="bob@x.com", password="pw12345!")
        self.carol = User.objects.create_user(email="carol@x.com", password="pw12345!")

        self.org_a = Organization.objects.create(name="Org A")
        self.org_b = Organization.objects.create(name="Org B")
        self.org_a.add_member(self.alice, role=Role.OWNER)
        self.org_a.add_member(self.carol, role=Role.MEMBER)
        self.org_b.add_member(self.bob, role=Role.OWNER)

        self.proj_a = Project.objects.create(organization=self.org_a, name="A Project")
        self.proj_b = Project.objects.create(organization=self.org_b, name="B Project")

    def test_list_requires_authentication(self):
        resp = self.client.get(reverse("projects:list"))
        self.assertEqual(resp.status_code, 403)

    def test_list_only_shows_own_org_projects(self):
        self.client.force_login(self.alice)
        resp = self.client.get(reverse("projects:list"))
        self.assertEqual(resp.status_code, 200)
        ids = [p["id"] for p in resp.json()]
        self.assertEqual(ids, [self.proj_a.id])

    def test_cannot_retrieve_other_tenants_project(self):
        self.client.force_login(self.alice)
        resp = self.client.get(reverse("projects:detail", args=[self.proj_b.id]))
        self.assertEqual(resp.status_code, 404)

    def test_owner_can_create_project_and_gets_default_workspace(self):
        self.client.force_login(self.alice)
        resp = self.client.post(
            reverse("projects:list"),
            {"organization": self.org_a.id, "name": "New Site", "mode": "build"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 201, resp.content)
        body = resp.json()
        self.assertEqual(body["slug"], "new-site")
        self.assertEqual(body["created_by"], self.alice.id)
        created = Project.objects.get(id=body["id"])
        self.assertEqual(created.workspaces.filter(is_default=True).count(), 1)

    def test_member_cannot_create_project(self):
        # carol is only a plain member of org_a -> not in manageable orgs.
        self.client.force_login(self.carol)
        resp = self.client.post(
            reverse("projects:list"),
            {"organization": self.org_a.id, "name": "Nope"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 400)

    def test_cannot_create_project_in_foreign_org(self):
        self.client.force_login(self.alice)
        resp = self.client.post(
            reverse("projects:list"),
            {"organization": self.org_b.id, "name": "Sneaky"},
            content_type="application/json",
        )
        self.assertEqual(resp.status_code, 400)
