# Generated by Django 6.0.2 on 2026-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='daily_usd_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max USD of AI spend per day. Blank = use platform default / unlimited.', max_digits=10, null=True),
        ),
    ]
