# Generated by Django 6.0.2 on 2026-09-08 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditaccount_daily_usd_cap'),
        ('organizations', '0002_team_invitation_teammembership_team_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('subtotal_usd', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('credits_used', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization')),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_start'), name='uniq_invoice_period_per_org')],
            },
        ),
    ]
